
set(target "appApplication")
set(working_dir "/Users/shreetej721/Desktop/QT Projects/Application")
set(src_and_dest_list
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/Bell.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/Bell.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/Menu.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/Menu.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/User.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/User.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/PowerOff.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/PowerOff.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/Back.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/Back.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/AuditTrail.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/AuditTrail.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/FactorySettings.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets//images/FactorySettings.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/More.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/More.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/ProductLib.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/ProductLib.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/Settings.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/Settings.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/UserCircle.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/UserCircle.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/userNew.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/userNew.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/updated.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/updated.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/usbupdate.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/usbupdate.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/supplier.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/supplier.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/bug.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/bug.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/coding.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/coding.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/social.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/social.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/diagnosis.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets//images//diagnosis.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/calendar.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/calendar.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/assets/images/filter.png"
    "/Users/shreetej721/Desktop/QT Projects/Application/Application/assets/images/filter.png"

)
set(timestamp_file "/Users/shreetej721/Desktop/QT Projects/Application/.qt/appApplication_res.txt")
