#include "PdfExporter.h"

#include <QPdfWriter>
#include <QPainter>
#include <QPageSize>
#include <QStandardPaths>
#include <QDir>
#include <QFileInfo>
#include <QDateTime>
#include <QDebug>

#include <QDesktopServices>
#include <QUrl>
#include <QFile>

PdfExporter::PdfExporter(QObject *parent)
    : QObject(parent)
{
}

// ================= GET / CREATE REPORTS FOLDER =================
QString PdfExporter::getReportsFolderPath()
{
    QString basePath =
        QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation);

    QString folderPath = basePath + "/Reports Folder";

    QDir dir(folderPath);
    if (!dir.exists()) {
        dir.mkpath(".");
        qDebug() << "Reports Folder created at:" << folderPath;
    }

    return folderPath;
}
// ================= GET ALL PDFs =================
QStringList PdfExporter::getAllPdfFiles()
{
    QString folder = getReportsFolderPath();

    QDir dir(folder);
    QStringList files = dir.entryList(QStringList() << "*.pdf",
                                      QDir::Files,
                                      QDir::Time); // latest first

    QStringList fullPaths;
    for (const QString &f : files)
        fullPaths << dir.absoluteFilePath(f);

    return fullPaths;
}

// ================= DELETE PDF =================
bool PdfExporter::deletePdf(const QString &filePath)
{
    QFile file(filePath);
    if (file.exists()) {
        return file.remove();
    }
    return false;
}

// ================= OPEN PDF =================
void PdfExporter::openPdf(const QString &filePath)
{
    QDesktopServices::openUrl(QUrl::fromLocalFile(filePath));
}

// ================= EXPORT PDF =================
QString PdfExporter::exportTableToPdf(const QVariantList &data,
                                      const QString &fromDate,
                                      const QString &toDate,
                                      const QString &filePath)
{
    QString path = filePath;

    //  FORCE SAVE INSIDE REPORTS FOLDER
    if (path.isEmpty()) {
        QString ts = QDateTime::currentDateTime().toString("dd-MM-yyyy_HH-mm-ss");

        QString folder = getReportsFolderPath();

        path = folder + "/Audit_Report_" + ts + ".pdf";
    }

    QDir().mkpath(QFileInfo(path).absolutePath());

    QPdfWriter writer(path);
    writer.setPageSize(QPageSize(QPageSize::A4));
    writer.setResolution(96);
    writer.setPageMargins(QMarginsF(15,15,15,15));

    QPainter painter(&writer);

    const int pageWidth  = writer.width();

    const int rowHeight = 20;
    const int yStart    = 160;

    const int colWidths[] = {
        50, 90, 80, 90, 100, 100,
        pageWidth - 510
    };

    int totalRows = data.size();
    QString now = QDateTime::currentDateTime().toString("dd/MM/yyyy HH:mm:ss");

    // ================= HEADER =================
    auto drawHeader = [&](int page, int totalPages)
    {
        painter.setFont(QFont("Arial", 12, QFont::Bold));
        painter.drawText(QRect(0, 20, pageWidth, 25),
                         Qt::AlignCenter,
                         "A&D Instruments (India) Pvt Ltd.");

        if (page == 0)
        {
            painter.drawText(QRect(0, 45, pageWidth, 25),
                             Qt::AlignCenter,
                             "AUDIT TRAIL REPORT");

            painter.setFont(QFont("Arial", 9));

            painter.drawText(20, 90, "From: " + fromDate);
            painter.drawText(pageWidth/3, 90, "Customer: ---");
            painter.drawText(2*pageWidth/3, 90, "Machine ID: PHMX");

            painter.drawText(20, 110, "To: " + toDate);
            painter.drawText(pageWidth/3, 110, "Location: ---");
            painter.drawText(2*pageWidth/3, 110,
                             "Page: " + QString::number(page+1) + "/" + QString::number(totalPages));

            painter.drawText(20, 130, "File Created: " + now);
        }
        else
        {
            painter.setFont(QFont("Arial", 9));
            painter.drawText(20, 90, "Machine ID: PHMX");
            painter.drawText(pageWidth/3, 90, "Generated: " + now);
            painter.drawText(2*pageWidth/3, 90,
                             "Page: " + QString::number(page+1) + "/" + QString::number(totalPages));
        }
    };

    // ================= FOOTER =================
    auto drawFooter = [&]()
    {
        painter.setFont(QFont("Arial", 9, QFont::Bold));

        QRect pageRect = writer.pageLayout().paintRectPixels(writer.resolution());

        int left   = pageRect.left();
        int right  = pageRect.right();
        int bottom = pageRect.bottom();

        int y = bottom - 10;

        painter.drawText(left, y, "Generated By: ADMIN");
        painter.drawText(right - 200, y, "Approved By: ADMIN");
    };

    int dataIndex = 0;
    int page = 0;

    while (dataIndex < totalRows || page == 0)
    {
        if (page > 0)
            writer.newPage();

        int totalPagesEstimate =
            (totalRows == 0) ? 1 : (totalRows / 45) + 1;

        drawHeader(page, totalPagesEstimate);

        int y = yStart;

        QRect pageRect = writer.pageLayout().paintRectPixels(writer.resolution());
        int footerTopY = pageRect.bottom() - 40;

        // ===== TABLE HEADER =====
        QStringList headers = {"S/No","Date","Time","User","Old","New","Details"};

        painter.setFont(QFont("Arial", 9, QFont::Bold));

        int x = 0;
        for (int i = 0; i < headers.size(); ++i)
        {
            painter.drawRect(x, y, colWidths[i], rowHeight);
            painter.drawText(QRect(x, y, colWidths[i], rowHeight),
                             Qt::AlignCenter, headers[i]);
            x += colWidths[i];
        }

        y += rowHeight;

        painter.setFont(QFont("Arial", 9));

        // ===== DATA ROWS =====
        while (dataIndex < totalRows)
        {
            if (y + rowHeight > footerTopY)
                break;

            QVariantMap m = data[dataIndex].toMap();

            QStringList row = {
                m["sr"].toString(),
                m["date"].toString(),
                m["time"].toString(),
                m["user"].toString(),
                m["old"].toString(),
                m["newVal"].toString(),
                m["remark"].toString()
            };

            int x = 0;

            for (int c = 0; c < row.size(); ++c)
            {
                painter.drawRect(x, y, colWidths[c], rowHeight);

                painter.drawText(QRect(x+4, y, colWidths[c]-8, rowHeight),
                                 Qt::AlignVCenter | Qt::AlignLeft,
                                 row[c]);

                x += colWidths[c];
            }

            y += rowHeight;
            dataIndex++;
        }

        drawFooter();
        page++;
    }

    painter.end();

    qDebug() << "PDF saved at:" << path;
    return path;
}
