#include "PdfExporter.h"
#include "DatabaseManager.h"

#include <QDesktopServices>
#include <QUrl>
#include <QFile>

#include <QApplication>
#include <QPdfWriter>
#include <QPainter>
#include <QFont>
#include <QFontDatabase>
#include <QPixmap>
#include <QStandardPaths>
#include <QDateTime>
#include <QDir>
#include <QFileInfo>
#include <QVariantList>
#include <QVariantMap>
#include <QStringList>
#include <QRect>
#include <QPageSize>
#include <QMarginsF>
#include <QDebug>
#include <QImage>
#include <QFile>
#include <QPageLayout>


PdfExporter::PdfExporter(QObject *parent)
    : QObject(parent)
{
}

// ================= GET / CREATE REPORTS FOLDER =================
QString PdfExporter::getReportsFolderPath()
{
    QString basePath =
        QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation);

    QString folderPath = basePath + "/Reports Folder";

    QDir dir(folderPath);
    if (!dir.exists()) {
        dir.mkpath(".");
        qDebug() << "Reports Folder created at:" << folderPath;
    }

    return folderPath;
}

// ================= GET ALL PDFs =================
QStringList PdfExporter::getAllPdfFiles()
{
    QString folder = getReportsFolderPath();

    QDir dir(folder);
    QStringList files = dir.entryList(QStringList() << "*.pdf",
                                      QDir::Files,
                                      QDir::Time);

    QStringList fullPaths;
    for (const QString &f : files)
        fullPaths << dir.absoluteFilePath(f);

    return fullPaths;
}

// ================= DELETE PDF =================
bool PdfExporter::deletePdf(const QString &filePath)
{
    QFile file(filePath);
    if (file.exists()) {
        return file.remove();
    }
    return false;
}

// ================= OPEN PDF =================
void PdfExporter::openPdf(const QString &filePath)
{
    QDesktopServices::openUrl(QUrl::fromLocalFile(filePath));
}

QVariantMap PdfExporter::getMachineDetails()
{
    DatabaseManager db;

    QVariantMap machineInfo =
        db.getMachineInfo();

    return machineInfo;
}

QString roleInitial(const QString& role)
{
    if(role.compare("Admin",Qt::CaseInsensitive)==0)
        return "A";

    if(role.compare("Supervisor",Qt::CaseInsensitive)==0)
        return "S";

    if(role.compare("Operator",Qt::CaseInsensitive)==0)
        return "O";

    return role.left(1).toUpper();
}

// ================= EXPORT AUDIT TRAIL PDF =================
QString PdfExporter::exportTableToPdf(const QVariantList &data,
                                      const QString &fromDate,
                                      const QString &toDate,
                                      const QString &filePath,
                                      const QVariantMap &sessionData)
{
    // ── PATH SETUP ──────────────────────────────────────────────────────────
    QString path = filePath;
    if (path.isEmpty()) {
        QString ts     = QDateTime::currentDateTime().toString("dd-MM-yyyy_HH-mm-ss");
        QString folder = getReportsFolderPath();
        path = folder + "/Audit_Report_" + ts + ".pdf";
    }
    QDir().mkpath(QFileInfo(path).absolutePath());

    QVariantMap machineInfo = getMachineDetails();


    QString companyName =
        machineInfo.value("supplierName")
            .toString();

    QString machineId =
        machineInfo.value("machineId")
            .toString();

    QString machineSerial =
        machineInfo.value("serialNumber")
            .toString();

    QString machineType =
        machineInfo.value("machineType").toString();

    QString location =
        machineInfo.value("location")
            .toString();

    QString userName =
        machineInfo.value("userName")
            .toString();


    QString loggedUser =
        sessionData.value("loggedInUserName","---")
            .toString();

    QString loggedRole =
        sessionData.value("loggedInUserRole","---")
            .toString();

    QString initial =
        roleInitial(loggedRole);

    // Footer left string built once, reused on every page
    QString footerLeftStr =
        QString("Generated By: %1 - %2      Approved By: %3 - %4")
            .arg(initial)
            .arg(loggedUser)
            .arg(initial)
            .arg(loggedUser);

    // ── WRITER ──────────────────────────────────────────────────────────────
    QPdfWriter writer(path);
    writer.setPageSize(QPageSize(QPageSize::A4));
    writer.setResolution(96);
    writer.setPageMargins(QMarginsF(0, 0, 0, 0));

    QPainter painter(&writer);

    // ── FONT ────────────────────────────────────────────────────────────────
    int fontId     = QFontDatabase::addApplicationFont(":/assets/images/RobotoCondensed-Regular.ttf");
    int fontBoldId = QFontDatabase::addApplicationFont(":/assets/images/RobotoCondensed-Bold.ttf");
    QString fontFamily = "Arial";
    if (fontId != -1) {
        QStringList families = QFontDatabase::applicationFontFamilies(fontId);
        if (!families.isEmpty()) fontFamily = families.first();
    }

    auto fontR = [&](int pt) { return QFont(fontFamily, pt, QFont::Normal); };
    auto fontB = [&](int pt) { return QFont(fontFamily, pt, QFont::Bold);   };

    // ── LOGO ────────────────────────────────────────────────────────────────
    QString logoPath = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation)
                       + "/Logo.png";
    QPixmap logo(logoPath);

    // ── PAGE GEOMETRY ───────────────────────────────────────────────────────
    const int pageW    = writer.width();
    const int pageH    = writer.height();
    const int marginL  = 40;
    const int marginR  = 40;
    const int marginT  = 20;
    const int marginB  = 30;
    const int contentW = pageW - marginL - marginR;

    // ── COLUMN WIDTHS ────────────────────────────────────────────────────────
    const int nCols = 7;
    int colW[nCols];
    colW[0] = 45;
    colW[1] = 80;
    colW[2] = 65;
    colW[3] = 80;
    colW[4] = 90;
    colW[5] = 90;
    colW[6] = contentW - (colW[0]+colW[1]+colW[2]+colW[3]+colW[4]+colW[5]);

    const int rowH      = 22;
    const int thH       = 24;
    const int lineThick = 2;
    const int thinLine  = 1;

    // ── PEN HELPER ───────────────────────────────────────────────────────────
    auto setPen = [&](int width, QColor color = Qt::black) {
        QPen p(color);
        p.setWidth(width);
        painter.setPen(p);
    };

    // ── LOGO HELPER ──────────────────────────────────────────────────────────
    auto drawLogo = [&]() {
        if (logo.isNull()) return;
        const int logoW = 130;
        const int logoH = 55;
        QRect logoRect(pageW - marginR - logoW, marginT, logoW, logoH);
        const int pad = 4;
        QSize scaled = logo.size().scaled(logoRect.size() - QSize(2*pad, 2*pad),
                                          Qt::KeepAspectRatio);
        QRect target(logoRect.center().x() - scaled.width()/2,
                     logoRect.center().y() - scaled.height()/2,
                     scaled.width(), scaled.height());
        painter.drawPixmap(target, logo);
    };

    const int headerFullH    = 148;
    const int headerCompactH = 65;
    const int footerH        = 38;

    auto rowsPerPage = [&](int pg) -> int {
        int hdrH      = (pg == 0) ? headerFullH : headerCompactH;
        int available = pageH - marginT - hdrH - footerH - marginB - thH;
        return available / rowH;
    };

    int totalRows  = data.size();
    int totalPages = 0;
    {
        int counted = 0;
        int pg      = 0;
        if (totalRows == 0) {
            totalPages = 1;
        } else {
            while (counted < totalRows) {
                counted += rowsPerPage(pg);
                pg++;
            }
            totalPages = pg;
        }
    }

    // ── DRAW HEADER FULL (page 0) ────────────────────────────────────────────
    auto drawHeaderFull = [&](int pageNum) {
        int y = marginT;

        painter.setFont(fontB(12));
        setPen(1);
        painter.drawText(QRect(marginL, y, contentW, 22),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         companyName);                          // ← was hardcoded
        y += 22;

        painter.setFont(fontB(11));
        painter.drawText(QRect(marginL, y, contentW, 20),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         "AUDIT TRAIL REPORT");
        y += 20;

        painter.setFont(fontR(9));
        painter.drawText(QRect(marginL, y, contentW, 16),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         "(Metal Detector)");
        y += 16;

        drawLogo();

        setPen(lineThick);
        painter.drawLine(marginL, y + 4, pageW - marginR, y + 4);
        y += 12;

        painter.setFont(fontR(9));
        setPen(1);

        int col1x     = marginL;
        int col2x     = marginL + contentW / 3;
        int col3x     = marginL + 2 * contentW / 3;
        int metaLineH = 18;

        auto drawMeta = [&](int x, int yy, const QString &label, const QString &val) {
            constexpr int colonOffset = 78;
            painter.setFont(fontB(9));
            painter.drawText(x, yy, label);
            painter.setFont(fontR(9));
            painter.drawText(x + colonOffset, yy, ": " + val);
        };

        QString now = QDateTime::currentDateTime().toString("dd/MM/yyyy @ HH:mm:ss");

        // Row 1
        drawMeta(col1x, y + metaLineH,   "User",         userName);      // ← was "---"
        drawMeta(col2x, y + metaLineH,   "File Created", now);
        drawMeta(col3x, y + metaLineH,   "Machine ID",   machineId);     // ← was "PHMX"

        // Row 2
        drawMeta(col1x, y + 2*metaLineH, "Location",     location);      // ← was "---"
        drawMeta(col2x, y + 2*metaLineH, "From",         fromDate);
        drawMeta(col3x, y + 2*metaLineH, "M/c Sr. No.",  machineSerial); // ← was "---"
        drawMeta(col3x, y + 3*metaLineH, "M/c Type",     machineType);

        // Row 3
        drawMeta(col2x, y + 3*metaLineH, "To",           toDate);

        y += 3*metaLineH + 6;

        setPen(lineThick);
        painter.drawLine(marginL, y + 4, pageW - marginR, y + 4);
        y += 20;

        return y;
    };

    // ── DRAW HEADER COMPACT (page 1+) ────────────────────────────────────────
    auto drawHeaderCompact = [&](int pageNum) {
        int y = marginT;

        painter.setFont(fontB(11));
        setPen(1);
        painter.drawText(QRect(marginL, y, contentW, 22),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         companyName);                          // ← was hardcoded
        y += 22;

        drawLogo();

        painter.setFont(fontR(9));
        QString now = QDateTime::currentDateTime().toString("dd/MM/yyyy HH:mm:ss");

        int col1x = marginL;
        int col2x = marginL + contentW / 3;
        int col3x = marginL + 2 * contentW / 3;

        y += 22;

        setPen(lineThick);
        painter.drawLine(marginL, y + 4, pageW - marginR, y + 4);
        y += 20;

        return y;
    };

    // ── TABLE HEADER ROW ─────────────────────────────────────────────────────
    QStringList headers = {"S/No", "Date", "Time", "User", "Old Value", "New Value", "Details / Remarks"};

    auto drawTableHeader = [&](int y) {
        const int    radius    = 6;
        const QColor headerBg  (52, 58, 64);
        const QColor headerText(Qt::white);

        painter.save();
        painter.setPen(Qt::NoPen);
        painter.setBrush(headerBg);
        painter.drawRoundedRect(marginL, y, contentW, thH, radius, radius);
        painter.setPen(headerText);
        painter.setFont(fontB(9));

        int x = marginL;
        for (int i = 0; i < nCols; ++i) {
            painter.drawText(QRect(x + 6, y, colW[i] - 12, thH),
                             Qt::AlignCenter, headers[i]);
            x += colW[i];
        }
        painter.restore();
        return y + thH + 4;
    };

    // ── FOOTER ───────────────────────────────────────────────────────────────
    auto drawFooter = [&](int pageNum) {
        int footerY     = pageH - marginB - 22;
        int footerDivY  = footerY - 8;
        int footerTextY = footerY + 12;

        setPen(lineThick);
        painter.drawLine(marginL, footerDivY, pageW - marginR, footerDivY);

        painter.setFont(fontB(9));
        setPen(1);

        painter.drawText(marginL, footerTextY, footerLeftStr); // ← was hardcoded

        QString repLabel = "Audit Trail Report";
        QString pageStr  = QString("Page No: %1 / %2")
                              .arg(pageNum + 1).arg(totalPages);

        QFontMetrics fm       = painter.fontMetrics();
        int repLabelW         = fm.horizontalAdvance(repLabel);
        int pageStrW          = fm.horizontalAdvance(pageStr);
        int sepW              = 10;
        int sepLineW          = 2;
        int blockW            = repLabelW + sepW + sepLineW + sepW + pageStrW;
        int blockX            = pageW - marginR - blockW;

        painter.drawText(blockX, footerTextY, repLabel);

        int sepX = blockX + repLabelW + sepW;
        setPen(lineThick);
        painter.drawLine(sepX, footerDivY + 8, sepX, footerTextY - 1);

        setPen(1);
        painter.drawText(sepX + sepW, footerTextY, pageStr);
    };

    // ── MAIN RENDER LOOP ─────────────────────────────────────────────────────
    int dataIndex = 0;
    int page      = 0;

    while (dataIndex < totalRows || page == 0) {
        if (page > 0)
            writer.newPage();

        int tableTop;
        if (page == 0)
            tableTop = drawHeaderFull(page);
        else
            tableTop = drawHeaderCompact(page);

        int y          = drawTableHeader(tableTop);
        int footerTopY = pageH - marginB - 22 - 12;

        painter.setFont(fontR(9));

        while (dataIndex < totalRows) {
            if (y + rowH > footerTopY)
                break;

            QVariantMap m = data[dataIndex].toMap();
            QStringList row = {
                m["sr"].toString(),
                m["date"].toString(),
                m["time"].toString(),
                m["user"].toString(),
                m["old"].toString(),
                m["newVal"].toString(),
                m["remark"].toString()
            };

            if (dataIndex % 2)
                painter.fillRect(marginL, y, contentW, rowH, QColor(220, 235, 255));

            int x = marginL;
            for (int c = 0; c < nCols; ++c) {
                painter.setFont(fontR(9));
                painter.setPen(QColor(45, 45, 45));

                Qt::Alignment align;
                if      (c == 0) align = Qt::AlignCenter;
                else if (c == 6) align = Qt::AlignLeft | Qt::AlignVCenter;
                else             align = Qt::AlignCenter;

                painter.drawText(QRect(x + 6, y, colW[c] - 12, rowH), align, row[c]);
                x += colW[c];
            }

            setPen(1, QColor(230, 230, 230));
            painter.drawLine(marginL + 12, y + rowH + 2,
                             marginL + contentW - 12, y + rowH + 2);

            y += rowH;
            dataIndex++;
        }

        drawFooter(page);
        page++;
    }

    painter.end();
    qDebug() << "PDF saved at:" << path;
    return path;
}

// ================= EXPORT BATCH / PRODUCT PDF =================
QString PdfExporter::exportBatchToPdf(const QVariantMap  &batchData,
                                      const QVariantList &rejectionData,
                                      const QVariantMap &sessionData,
                                      const QString      &filePath)
{   
    // ── PATH SETUP ───────────────────────────────────────────────────────────
    QString path = filePath;
    if (path.isEmpty()) {
        QString ts     = QDateTime::currentDateTime().toString("dd-MM-yyyy_HH-mm-ss");
        QString folder = getReportsFolderPath();
        path = folder + "/Batch_Report_" + ts + ".pdf";
    }
    QDir().mkpath(QFileInfo(path).absolutePath());

    // ── WRITER ───────────────────────────────────────────────────────────────
    QPdfWriter writer(path);
    writer.setPageSize(QPageSize(QPageSize::A4));
    writer.setResolution(96);
    writer.setPageMargins(QMarginsF(0, 0, 0, 0));

    QPainter painter(&writer);

    // ── FONT ─────────────────────────────────────────────────────────────────
    int fontId = QFontDatabase::addApplicationFont(":/fonts/RobotoCondensed-Regular.ttf");
    QFontDatabase::addApplicationFont(":/fonts/RobotoCondensed-Bold.ttf");
    QString fontFamily = "Arial";
    if (fontId != -1) {
        QStringList fams = QFontDatabase::applicationFontFamilies(fontId);
        if (!fams.isEmpty()) fontFamily = fams.first();
    }
    auto fontR = [&](int pt) { return QFont(fontFamily, pt, QFont::Normal); };
    auto fontB = [&](int pt) { return QFont(fontFamily, pt, QFont::Bold);   };

    // ── LOGO ─────────────────────────────────────────────────────────────────
    QString logoPath = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation)
                       + "/Logo.png";
    QPixmap logo(logoPath);

    // ── PAGE GEOMETRY ────────────────────────────────────────────────────────
    const int pageW    = writer.width();
    const int pageH    = writer.height();
    const int marginL  = 40;
    const int marginR  = 40;
    const int marginT  = 20;
    const int marginB  = 30;
    const int contentW = pageW - marginL - marginR;

    // ── DUAL TABLE GEOMETRY ──────────────────────────────────────────────────
    const int tableSectionGap = 14;
    const int sectionW        = (contentW - tableSectionGap) / 2;

    const int nCols = 4;
    int colW[nCols];
    colW[0] = 36;
    colW[1] = 68;
    colW[2] = 62;
    colW[3] = sectionW - colW[0] - colW[1] - colW[2];

    const int rowH      = 22;
    const int thH       = 26;
    const int lineThick = 2;

    // ── PEN HELPER ───────────────────────────────────────────────────────────
    auto setPen = [&](int w, QColor c = Qt::black) {
        QPen p(c); p.setWidth(w); painter.setPen(p);
    };

    // ── LOGO HELPER ──────────────────────────────────────────────────────────
    auto drawLogo = [&]() {
        if (logo.isNull()) return;
        const int lw = 130, lh = 52, pad = 4;
        QRect lr(pageW - marginR - lw, marginT, lw, lh);
        QSize sc = logo.size().scaled(lr.size() - QSize(2*pad, 2*pad), Qt::KeepAspectRatio);
        QRect tg(lr.center().x() - sc.width()/2,
                 lr.center().y() - sc.height()/2,
                 sc.width(), sc.height());
        painter.drawPixmap(tg, logo);
    };

    // ── BATCH DATA ───────────────────────────────────────────────────────────
    QString now         = QDateTime::currentDateTime().toString("dd/MM/yyyy @ HH:mm:ss");
    QString batchName   = batchData["batch"].toString();
    QString productName = batchData["product"].toString();
    QString started     = batchData["started"].toString();
    QString ended       = batchData["ended"].toString();
    QString productCode = batchData.value("productCode",    "default code").toString();
    QString productSno  = batchData.value("productSno",     "01-001").toString();
    QString totalDur    = batchData.value("totalDuration",  "---").toString();
    QString runDur      = batchData.value("runDuration",    "---").toString();
    QString pauseDur    = batchData.value("pauseDuration",  "---").toString();


    // ── IDENTITY / SESSION DATA (all previously hardcoded) ───────────────────

    QVariantMap machineInfo = getMachineDetails();

    QString companyName = machineInfo.value("supplierName", "---").toString();
    QString machineId   = machineInfo.value("machineId", "---").toString();
    QString serialNo    = machineInfo.value("serialNumber", "---").toString();
    QString machineType = machineInfo.value("machineType", "---").toString();
    QString location    = machineInfo.value("location", "---").toString();
    QString userName    = machineInfo.value("userName", "---").toString();


    QString loggedUser =
        sessionData.value("loggedInUserName","---")
            .toString();

    QString loggedRole =
        sessionData.value("loggedInUserRole","---")
            .toString();

    QString initial =
        roleInitial(loggedRole);

    // Footer left string built once, reused on every page
    QString footerLeftStr =
        QString("Generated By: %1 - %2      Approved By: %3 - %4")
            .arg(initial)
            .arg(loggedUser)
            .arg(initial)
            .arg(loggedUser);

    int totalRej = 0;
    for (const QVariant &v : rejectionData) {
        QVariantMap m     = v.toMap();
        QString eventType = m.value("eventType", "").toString().toLower();
        if (eventType.isEmpty() || eventType == "reject")
            totalRej += m["rejectCount"].toInt();
    }

    QString endText = (ended == "---" || ended.isEmpty())
                          ? "Batch is still running...."
                          : ended;

    // ── FOOTER ZONE ──────────────────────────────────────────────────────────
    const int footerDivY  = pageH - marginB - 28;
    const int footerTextY = pageH - marginB - 10;

    // ── DRAW FOOTER ──────────────────────────────────────────────────────────
    auto drawFooter = [&](int pageNum, int totalPages) {
        setPen(lineThick);
        painter.drawLine(marginL, footerDivY, pageW - marginR, footerDivY);

        painter.setFont(fontB(9));
        setPen(1);
        painter.drawText(marginL, footerTextY, footerLeftStr); // ← was hardcoded

        QString repLabel = "Batch Report";
        QString pageStr  = QString("Page No: %1 / %2").arg(pageNum + 1).arg(totalPages);

        QFontMetrics fm   = painter.fontMetrics();
        int repLabelW     = fm.horizontalAdvance(repLabel);
        int pageStrW      = fm.horizontalAdvance(pageStr);
        int sepW          = 10;
        int sepLineW      = 2;
        int blockW        = repLabelW + sepW + sepLineW + sepW + pageStrW;
        int blockX        = pageW - marginR - blockW;

        painter.drawText(blockX, footerTextY, repLabel);

        int sepX = blockX + repLabelW + sepW;
        setPen(lineThick);
        painter.drawLine(sepX, footerDivY + 8, sepX, footerTextY - 1);

        setPen(1);
        painter.setFont(fontB(9));
        painter.drawText(sepX + sepW, footerTextY, pageStr);
    };

    // ── DRAW FULL HEADER (page 0) ─────────────────────────────────────────
    auto drawHeaderFull = [&]() -> int {
        int y = marginT;
        drawLogo();

        setPen(1);
        painter.setFont(fontB(12));
        painter.drawText(QRect(marginL, y, contentW, 22),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         companyName);                          // ← was hardcoded
        y += 22;

        painter.setFont(fontB(10));
        painter.drawText(QRect(marginL, y, contentW, 20),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         "PRODUCT / BATCH REPORT");
        y += 20;

        painter.setFont(fontR(9));
        painter.drawText(QRect(marginL, y, contentW, 16),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         "(Metal Detector)");
        y += 16;

        int logoBottom = marginT + 52 + 6;
        if (y + 3 < logoBottom)
            y = logoBottom;

        setPen(lineThick);
        painter.drawLine(marginL, y + 3, pageW - marginR, y + 3);
        y += 10;

        setPen(1);
        painter.setFont(fontR(9));
        painter.drawText(marginL, y + 12, "File created on: " + now);
        y += 25;

        return y;
    };

    // ── DRAW COMPACT HEADER (page 1+) ────────────────────────────────────
    auto drawHeaderCompact = [&](int pageNum, int totalPages) -> int {
        Q_UNUSED(totalPages)
        int y = marginT;
        drawLogo();

        setPen(1);
        painter.setFont(fontB(11));
        painter.drawText(QRect(marginL, y, contentW, 22),
                         Qt::AlignHCenter | Qt::AlignVCenter,
                         companyName);                          // ← was hardcoded
        y += 22;

        int logoBottom = marginT + 52 + 6;
        if (y + 2 < logoBottom)
            y = logoBottom;

        setPen(lineThick);
        painter.drawLine(marginL, y + 2, pageW - marginR, y + 2);
        y += 12;

        int c1 = marginL;
        int c2 = marginL + contentW / 3;

        painter.setFont(fontB(9)); setPen(1);
        painter.drawText(c1, y + 12, "Machine ID:");
        painter.setFont(fontR(9));
        painter.drawText(c1 + 72, y + 12, machineId);          // ← was "PHMX"

        painter.setFont(fontB(9));
        painter.drawText(c2, y + 12, "Generated:");
        painter.setFont(fontR(9));
        painter.drawText(c2 + 68, y + 12, now);

        y += 20;

        setPen(lineThick);
        painter.drawLine(marginL, y + 2, pageW - marginR, y + 2);
        y += 10;

        return y;
    };

    // ── DRAW TABLE HEADER ROW (for one half-section) ─────────────────────
    QStringList tHeaders = {"S/No.", "Date", "Time", "Reject Count / Batch Status"};
    auto drawTableHeader = [&](int xOffset, int y) -> int {
        const int    radius    = 6;
        const QColor headerBg  (52, 58, 64);
        const QColor headerText(Qt::white);

        painter.save();
        painter.setPen(Qt::NoPen);
        painter.setBrush(headerBg);
        painter.drawRoundedRect(xOffset, y, sectionW, thH, radius, radius);
        painter.setPen(headerText);
        painter.setFont(fontB(9));

        int x = xOffset;
        for (int i = 0; i < nCols; ++i) {
            painter.drawText(QRect(x + 4, y, colW[i] - 8, thH),
                             Qt::AlignCenter, tHeaders[i]);
            x += colW[i];
        }
        painter.restore();
        return y + thH + 4;
    };

    // ── STATUS DISPLAY HELPER ─────────────────────────────────────────────
    struct RowDisplay {
        QString text;
        QColor  color;
        bool    bold;
    };
    auto resolveRowDisplay = [&](const QVariantMap &m) -> RowDisplay {
        QString eventType = m.value("eventType", "").toString().toLower();
        if (eventType == "start")  return { "Batch Start",   QColor(20, 130, 20),  true  };
        if (eventType == "pause")  return { "Batch Paused",  QColor(200, 80, 0),   true  };
        if (eventType == "resume") return { "Batch Resumed", QColor(0, 80, 180),   true  };
        if (eventType == "end")    return { "Batch End",     QColor(60, 60, 60),   true  };
        return { m["rejectCount"].toString(), Qt::black, false };
    };

    // ── DRAW ONE DATA ROW (for one half-section) ─────────────────────────
    auto drawDataRow = [&](int xOffset, int y, int idx, const QVariantMap &m) {
        if (idx % 2 == 1)
            painter.fillRect(xOffset, y, sectionW, rowH, QColor(230, 230, 230));

        RowDisplay rd = resolveRowDisplay(m);

        QStringList row = {
            QString::number(idx + 1),
            m["date"].toString(),
            m["time"].toString(),
            rd.text
        };

        int x = xOffset;
        for (int c = 0; c < nCols; ++c) {
            setPen(1, QColor(210, 210, 210));
            painter.drawLine(xOffset + 8, y + rowH - 1,
                             xOffset + sectionW - 8, y + rowH - 1);

            Qt::Alignment al = (c == 0)
                                   ? (Qt::AlignVCenter | Qt::AlignHCenter)
                                   : (Qt::AlignVCenter | Qt::AlignLeft);

            if (c == nCols - 1) {
                painter.setFont(rd.bold ? fontB(8) : fontR(9));
                setPen(1, rd.color);
            } else {
                painter.setFont(fontR(9));
                setPen(1, QColor(45, 45, 45));
            }

            painter.drawText(QRect(x + 4, y, colW[c] - 8, rowH), al, row[c]);
            x += colW[c];
        }
    };

    // ── SECTION BOX HELPER ───────────────────────────────────────────────
    auto drawSectionTitle = [&](int y, const QString &title) -> int {
        painter.setFont(fontB(10));
        setPen(1);
        painter.drawText(marginL, y + 12, title);
        return y + 16;
    };

    auto drawKVLine = [&](int x, int y, const QString &lbl, const QString &val,
                          int valueOffsetX = 145) {
        painter.setFont(fontB(9)); setPen(1);
        painter.drawText(x + 8, y, lbl);
        painter.setFont(fontR(9));
        painter.drawText(x + 8 + valueOffsetX, y, val);
    };

    // ── DRAW DUAL TABLE HEADERS ───────────────────────────────────────────
    auto drawBothTableHeaders = [&](int y) -> int {
        int leftX  = marginL;
        int rightX = marginL + sectionW + tableSectionGap;
        drawTableHeader(leftX,  y);
        drawTableHeader(rightX, y);
        return y + thH + 4;
    };

    // ── DRAW VERTICAL SECTION DIVIDER ─────────────────────────────────────
    auto drawSectionDivider = [&](int yTop, int yBottom) {
        int divX = marginL + sectionW + tableSectionGap / 2;
        QPen dp(QColor(180, 180, 180));
        dp.setWidth(1);
        dp.setStyle(Qt::DashLine);
        painter.setPen(dp);
        painter.drawLine(divX, yTop, divX, yBottom);
        setPen(1);
    };

    // ── DRAW TOTAL ROW ────────────────────────────────────────────────────
    auto drawTotalRow = [&](int xOffset, int y) {
        painter.setFont(fontB(9));
        setPen(1, Qt::black);
        QString totalStr = "Total Rejection Count: " + QString::number(totalRej);
        painter.drawText(QRect(xOffset, y + 2, sectionW - 4, rowH - 4),
                         Qt::AlignVCenter | Qt::AlignRight, totalStr);
    };

    // ── PRE-CALCULATE TOTAL PAGES ────────────────────────────────────────
    const int footerH      = pageH - footerDivY + 10;
    const int summaryH     = 74 + 16 + 62 + 16 + 172 + 16 + 34 + 16 + 24;
    const int availPage0   = pageH - summaryH - footerH - 10;
    const int rowPairsPage0 = qMax(0, availPage0 / rowH);
    const int rowsPage0    = rowPairsPage0 * 2;

    const int compactHdrH   = 76;
    const int availPageN    = pageH - compactHdrH - thH - footerH - marginB - 20;
    const int rowPairsPageN = qMax(1, availPageN / rowH);
    const int rowsPageN     = rowPairsPageN * 2;

    int totalPages = 1;
    if (!rejectionData.isEmpty() && rejectionData.size() > rowsPage0) {
        int remaining = rejectionData.size() - rowsPage0;
        totalPages += (remaining + rowsPageN - 1) / rowsPageN;
    }

    // ════════════════════════════════════════════════════════════════════
    // PAGE 0
    // ════════════════════════════════════════════════════════════════════
    int y = drawHeaderFull();

    // ── Machine Summary ──────────────────────────────────────────────────
    y = drawSectionTitle(y, "Machine Summary :");
    y += 10;
    int boxTop = y;
    int lColX  = marginL;
    int rColX  = marginL + contentW / 2;
    int r1y    = boxTop + 26;
    int r2y    = boxTop + 43;
    y += 10;
    drawKVLine(lColX, r1y, "User",        ": " + userName);         // ← was "---"
    drawKVLine(rColX, r1y, "Machine ID.",  ": " + machineId,  90);   // ← was "PHMX"
    drawKVLine(rColX, r2y, "M/c Sr. No.", ": " + serialNo,   90);
    drawKVLine(lColX, r2y + 17, "M/c Type", ": " + machineType);
    drawKVLine(lColX, r2y, "Location",    ": " + location);    // ← was "---
    int machineBoxH = 72;
    setPen(lineThick);
    painter.drawRect(marginL, boxTop, contentW, machineBoxH);
    y = boxTop + machineBoxH + 10;

    // ── Product / Batch Summary ──────────────────────────────────────────
    y = drawSectionTitle(y, "Product / Batch Summary :");
    y += 10;
    boxTop = y;

    struct KVPair { QString lbl; QString val; };
    QList<KVPair> leftRows = {
        {"Product Loaded on", ": " + started},
        {"Product Loaded by", ": Machine"},
        {"Product Code",      ": " + productCode},
        {"Product S/No.",      ": " + productSno},
        {"Product Name",      ": " + productName},
        {"", ""}
    };
    QList<KVPair> rightRows = {
                               {"Batch ID",           ": " + batchName},
                               {"Batch Start Time",     ": " + started},
                               {"Batch End Time",       ": " + endText},
                               {"Batch Run Duration",   ": " + runDur},
                               {"Batch Pause Duration", ": " + pauseDur},
                               {"Total Batch Duration", ": " + totalDur},
                               };

    int nKVRows   = leftRows.size();
    int lineH     = 17;
    int boxPadTop = 24;

    for (int i = 0; i < nKVRows; ++i) {
        int rowY = boxTop + boxPadTop + i * lineH;
        drawKVLine(lColX, rowY, leftRows[i].lbl, leftRows[i].val);
        if (!rightRows[i].lbl.isEmpty())
            drawKVLine(rColX, rowY, rightRows[i].lbl, rightRows[i].val, 155);
    }

    int productBoxH = boxPadTop + nKVRows * lineH + 8;
    setPen(lineThick);
    painter.drawRect(marginL, boxTop, contentW, productBoxH);
    y = boxTop + productBoxH + 10;

    // ── Rejection Summary ────────────────────────────────────────────────
    y = drawSectionTitle(y, "Rejection Summary :");
    y += 10;
    boxTop = y;
    drawKVLine(lColX, boxTop + 16, "Total Rejection Count  :", QString::number(totalRej));
    int rejBoxH = 28;
    setPen(lineThick);
    painter.drawRect(marginL, boxTop, contentW, rejBoxH);
    y = boxTop + rejBoxH + 10;

    y += 10;

    // ── Rejection Details — dual-column table (page 0) ───────────────────
    int dataIndex = 0;

    if (!rejectionData.isEmpty()) {
        painter.setFont(fontB(10)); setPen(1);
        painter.drawText(marginL, y + 12, "Rejection Details");
        y += 16;

        int leftX  = marginL;
        int rightX = marginL + sectionW + tableSectionGap;

        y = drawBothTableHeaders(y);

        int tableTopY   = y;
        int leftIdx     = dataIndex;
        int rightIdx    = dataIndex + rowPairsPage0;
        int rowY        = y;
        bool drewAnyRow = false;

        while (leftIdx < rejectionData.size()) {
            if (rowY + rowH > footerDivY - 6) break;

            drawDataRow(leftX, rowY, leftIdx, rejectionData[leftIdx].toMap());

            if (rightIdx < rejectionData.size())
                drawDataRow(rightX, rowY, rightIdx, rejectionData[rightIdx].toMap());

            drewAnyRow = true;
            rowY++;
            rowY += rowH - 1;
            leftIdx++;
            rightIdx++;
        }

        if (drewAnyRow)
            drawSectionDivider(tableTopY - 4, rowY);

        dataIndex = rightIdx;
        if (dataIndex > rejectionData.size())
            dataIndex = rejectionData.size();

        if (dataIndex >= rejectionData.size() && rowY + rowH <= footerDivY - 6)
            drawTotalRow(rightX, rowY);
    }

    drawFooter(0, totalPages);

    // ════════════════════════════════════════════════════════════════════
    // PAGES 1+ — rejection table continuation (dual-column)
    // ════════════════════════════════════════════════════════════════════
    int page = 1;
    while (dataIndex < rejectionData.size()) {
        writer.newPage();
        y = drawHeaderCompact(page, totalPages);

        painter.setFont(fontB(10)); setPen(1);
        painter.drawText(marginL, y + 12, "Rejection Details (continued)");
        y += 18;

        int leftX  = marginL;
        int rightX = marginL + sectionW + tableSectionGap;

        y = drawBothTableHeaders(y);

        int tableTopY = y;

        int rowsAvail = 0;
        {
            int testY = y;
            while (testY + rowH <= footerDivY - 6) { testY += rowH; rowsAvail++; }
        }

        int leftIdx  = dataIndex;
        int rightIdx = dataIndex + rowsAvail;
        int rowY     = y;
        bool drewAny = false;

        while (leftIdx < rejectionData.size()) {
            if (rowY + rowH > footerDivY - 6) break;

            drawDataRow(leftX, rowY, leftIdx, rejectionData[leftIdx].toMap());

            if (rightIdx < rejectionData.size())
                drawDataRow(rightX, rowY, rightIdx, rejectionData[rightIdx].toMap());

            drewAny = true;
            rowY   += rowH;
            leftIdx++;
            rightIdx++;
        }

        if (drewAny)
            drawSectionDivider(tableTopY - 4, rowY);

        dataIndex = rightIdx;
        if (dataIndex > rejectionData.size())
            dataIndex = rejectionData.size();

        if (dataIndex >= rejectionData.size() && rowY + rowH <= footerDivY - 6)
            drawTotalRow(rightX, rowY);

        drawFooter(page, totalPages);
        page++;
    }

    painter.end();
    qDebug() << "Batch PDF saved at:" << path;
    return path;
}

// =========== Check USB =========
bool PdfExporter::isUsbMounted()
{
    QDir mediaDir("/media");
    if (!mediaDir.exists())
        return false;

    QStringList users = mediaDir.entryList(QDir::Dirs | QDir::NoDotAndDotDot);
    for (const QString &user : users) {
        QDir userDir("/media/" + user);
        QStringList devices = userDir.entryList(QDir::Dirs | QDir::NoDotAndDotDot);
        if (!devices.isEmpty())
            return true;
    }
    return false;
}

// ============= Get USB path ==========
QString PdfExporter::getUsbPath()
{
    QDir mediaDir("/media");
    QStringList users = mediaDir.entryList(QDir::Dirs | QDir::NoDotAndDotDot);
    for (const QString &user : users) {
        QDir userDir("/media/" + user);
        QStringList devices = userDir.entryList(QDir::Dirs | QDir::NoDotAndDotDot);
        if (!devices.isEmpty())
            return "/media/" + user + "/" + devices.first();
    }
    return "";
}

// ============ Move selected files to USB ===========
bool PdfExporter::moveFilesToUsb(const QStringList &filePaths,
                                 const QString &serialNumber)
{
    QString usbPath = getUsbPath().trimmed();
    qDebug() << "USB Path :" << usbPath;

    if (usbPath.isEmpty()) {
        qDebug() << "USB path is empty";
        return false;
    }

    QString folderName = serialNumber.trimmed().isEmpty()
                             ? "Reports_MD"
                             : QString("Reports_MD_%1").arg(serialNumber.trimmed());

    QDir    usbDir(usbPath);
    QString destDir = usbDir.filePath(folderName);
    qDebug() << "Destination directory :" << destDir;

    if (!QDir().mkpath(destDir)) {
        qDebug() << "Failed to create directory";
        return false;
    }

    bool allOk = true;
    for (const QString &srcFile : filePaths) {
        QFileInfo fi(srcFile);
        if (!fi.exists()) {
            qDebug() << "Source file does not exist:" << srcFile;
            allOk = false;
            continue;
        }

        QString dstFile = QDir(destDir).filePath(fi.fileName());
        qDebug() << "Copying";
        qDebug() << "From :" << srcFile;
        qDebug() << "To   :" << dstFile;

        QFile::remove(dstFile);
        if (!QFile::copy(srcFile, dstFile)) {
            qDebug() << "Copy failed:" << srcFile;
            qDebug() << "Reason:" << QFile(srcFile).errorString();
            allOk = false;
        }
    }
    return allOk;
}

//====================== X-Y PLOT PDF ============================

QString PdfExporter::exportXYPlotToPdf(const QString &imagePath)
{
    QString reportsFolder = getReportsFolderPath();
    QDir().mkpath(reportsFolder);

    QString pdfName =
        QString("XY_Plot_%1.pdf")
            .arg(QDateTime::currentDateTime()
                     .toString("dd-MM-yyyy-HH-mm"));

    QString pdfPath = reportsFolder + "/" + pdfName;

    QPdfWriter writer(pdfPath);

    writer.setPageSize(QPageSize(QPageSize::A4));
    writer.setResolution(300);

    QPainter painter(&writer);

    painter.fillRect(writer.pageLayout().paintRectPixels(writer.resolution()),
                     Qt::white);

    QImage image(imagePath);

    if (!image.isNull()) {

        QRect page =
            writer.pageLayout().paintRectPixels(writer.resolution());

        QSize scaled =
            image.size().scaled(page.size() - QSize(120,120),
                                Qt::KeepAspectRatio);

        QRect target(
            (page.width()-scaled.width())/2,
            (page.height()-scaled.height())/2,
            scaled.width(),
            scaled.height());

        painter.drawImage(target, image);
    }

    painter.end();

    // Delete temporary image immediately
    QFile::remove(imagePath);

    return pdfPath;
}
